import{a as w,i,S as b}from"./assets/vendor-b2578120.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();async function p(r,s){const t="https://pixabay.com/api/",n={key:"43011845-ca4f94d8d544ea7c100ad449b",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s};return(await w.get(t,{params:n})).data}const u=document.querySelector(".gallery");function m(r){if(!r.length)i.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const s=r.map(t=>`<li class="item-image"><a class="photos-list-link" href="${t.largeImageURL}">
  <img class="photo" loading="lazy" src="${t.webformatURL}" alt="${t.tags}"/>
  </a>
  <ul class="photo-information-container">
  <li class="item-photo-information-container"><p><span class="accent">Likes</span>${t.likes}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Views</span>${t.views}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Comments</span>${t.comments}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Downloads</span>${t.downloads}</p></li>
  </ul>
  </li>`).join("");u.insertAdjacentHTML("beforeend",s),S.refresh()}}const S=new b(".gallery a",{captionsData:"alt",captionDelay:250}),h=document.querySelector(".loader"),f=document.querySelector(".search-form"),l=document.querySelector(".btn-load-more");function g(){h.classList.remove("is-hidden")}function y(){h.classList.add("is-hidden")}function P(){l.classList.remove("is-hidden")}function d(){l.classList.add("is-hidden")}let v,a=1,F=0;const M=15;f.addEventListener("submit",q);async function q(r){r.preventDefault(),d(),g(),u.innerHTML="",a=1;const s=r.target.elements.search.value.trim();if(s!=="")try{const t=await p(s,a);F=Math.ceil(t.totalHits/M),m(t.hits),L()}catch{i.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}else i.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});y(),f.reset()}l.addEventListener("click",E);async function E(){a+=1,d(),g();const r=await p(v,a);m(r.hits),y(),L()}function L(){a>=F?(d(),i.show({message:"We're sorry, but you've reached the end of search results.",theme:"dark",progressBarColor:"#FFFFFF",color:"blue",position:"topRight"})):P()}
//# sourceMappingURL=commonHelpers.js.map
