import{a as w,S as b,i}from"./assets/vendor-b2578120.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();async function u(o,r){const t="https://pixabay.com/api/",n={key:"43011845-ca4f94d8d544ea7c100ad449b",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await w.get(t,{params:n})).data}const l=document.querySelector(".gallery");function h(o){const r=o.map(t=>`<li class="item-image"><a class="photos-list-link" href="${t.largeImageURL}">
  <img class="photo" loading="lazy" src="${t.webformatURL}" alt="${t.tags}"/>
  </a>
  <ul class="photo-information-container">
  <li class="item-photo-information-container"><p><span class="accent">Likes</span>${t.likes}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Views</span>${t.views}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Comments</span>${t.comments}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Downloads</span>${t.downloads}</p></li>
  </ul>
  </li>`).join("");l.insertAdjacentHTML("beforeend",r),S.refresh()}const S=new b(".gallery a",{captionsData:"alt",captionDelay:250}),m=document.querySelector(".loader"),f=document.querySelector(".search-form"),d=document.querySelector(".btn-load-more");function g(){m.classList.remove("is-hidden")}function y(){m.classList.add("is-hidden")}function v(){d.classList.remove("is-hidden")}function p(){d.classList.add("is-hidden")}let P,a=1,F=0;const B=15;f.addEventListener("submit",M);async function M(o){o.preventDefault(),p(),g(),l.innerHTML="",a=1;const r=o.target.elements.search.value.trim();if(r||i.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),r!=="")try{const t=await u(r,a);F=Math.ceil(t.totalHits/B),h(t.hits),L()}catch{i.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}y(),f.reset()}d.addEventListener("click",R);async function R(){a+=1,p(),g();try{const o=await u(P,a);h(o.hits)}catch{i.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}y(),C(),L()}function L(){a>=F?(p(),i.show({message:"We're sorry, but you've reached the end of search results.",theme:"dark",progressBarColor:"#FFFFFF",color:"blue",position:"topRight"})):v()}function C(){const o=l.firstChild.getBoundingClientRect().height;scrollBy({top:o,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
